server:
  port: 8072  # Puerto para el servicio DTO

spring:
  application:
    name: dto
  cloud:
    config:
      uri: http://localhost:8888  # URL del Config Server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
