server:
  port: 8071  # Puerto para el servicio de autenticación

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/bd_auth
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    config:
      uri: http://localhost:8888  # URL del Config Server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    secret: tu_secreto_jwt
    expiration: 3600  # Expiración en segundos
    header: Authorization
    prefix: Bearer
