server:
  port: 8080  # Puerto del gateway

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Habilita el uso de Eureka para el enrutamiento basado en nombres de servicio
      routes:
        # Aquí puedes definir rutas personalizadas si es necesario
        - id: servicio-buses
          uri: lb://servicio-buses
          predicates:
            - Path=/buses/**
          filters:
            - StripPrefix=1  # Elimina el prefijo `/buses` para enrutar internamente

        - id: servicio-clientes
          uri: lb://servicio-clientes
          predicates:
            - Path=/clientes/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
