server:
  port: 8085  # Puerto del servicio de geolocalización

spring:
  application:
    name: servicio-geolocalizacion
  datasource:
    url: jdbc:mysql://localhost:3306/geolocalizacion_db  # URL de la base de datos
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Crear y actualizar las tablas automáticamente
    show-sql: true  # Muestra las consultas SQL en la consola

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
