server:
  port: 8073  # Puerto para el servicio de atención al cliente

spring:
  application:
    name: servicio-atencion-cliente
  datasource:
    url: jdbc:mysql://localhost:3306/atencion_cliente_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
