server:
  port: 8084  # Puerto del servicio de horarios

spring:
  application:
    name: servicio-horarios
  datasource:
    url: jdbc:mysql://localhost:3306/horarios_db  # URL de la base de datos
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Crea y actualiza las tablas automáticamente
    show-sql: true  # Muestra las consultas SQL en la consola

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
